// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {updater} from '../models';
import {ssh} from '../models';
import {main} from '../models';

export function AddTunnel(arg1:config.TunnelConfig):Promise<void>;

export function AuthorizePrivilegedBind():Promise<void>;

export function RestartApp():Promise<void>;

export function CancelSFTPTransfer(arg1:string):Promise<boolean>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearTunnelLogs(arg1:string):Promise<void>;

export function CloseSFTP(arg1:string):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function ConnectGroup(arg1:string):Promise<void>;

export function ConnectTunnel(arg1:string):Promise<void>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function DisconnectGroup(arg1:string):Promise<void>;

export function DisconnectTunnel(arg1:string):Promise<void>;

export function ExportTunnels(arg1:string,arg2:Array<string>):Promise<void>;

export function GetAutostart():Promise<boolean>;

export function GetCloseToTray():Promise<boolean>;

export function GetConfigFiles():Promise<Array<string>>;

export function GetCurrentVersion():Promise<string>;

export function GetIncludedConfigFiles():Promise<Array<config.ConfigFileInfo>>;

export function GetTunnelLogs(arg1:string):Promise<Array<config.LogEntry>>;

export function GetTunnelStatuses():Promise<Record<string, ssh.StatusEvent>>;

export function GetTunnels():Promise<Array<config.TunnelConfig>>;

export function ImportPreview(arg1:string):Promise<Array<config.TunnelConfig>>;

export function ImportTunnels(arg1:string,arg2:Array<string>):Promise<number>;

export function InstallUpdate():Promise<void>;

export function OpenSFTP(arg1:string):Promise<main.SFTPOpenResult>;

export function OpenTerminal(arg1:string):Promise<string>;

export function RenameGroup(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SFTPDelete(arg1:string,arg2:string):Promise<void>;

export function SFTPDownload(arg1:string,arg2:string):Promise<string>;

export function SFTPDownloadDir(arg1:string,arg2:string):Promise<string>;

export function SFTPListDir(arg1:string,arg2:string):Promise<Array<ssh.FileEntry>>;

export function SFTPMkdir(arg1:string,arg2:string):Promise<void>;

export function SFTPPickUploadFiles(arg1:string,arg2:string):Promise<main.SFTPUploadPick>;

export function SFTPReadText(arg1:string,arg2:string,arg3:boolean):Promise<ssh.TextFileResult>;

export function SFTPRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SFTPUploadFiles(arg1:string,arg2:Array<string>,arg3:string):Promise<number>;

export function SFTPWriteText(arg1:string,arg2:string,arg3:string,arg4:number):Promise<main.SFTPWriteResult>;

export function SelectFile():Promise<string>;

export function SelectSaveFile(arg1:string):Promise<string>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetTunnelPinned(arg1:string,arg2:boolean):Promise<void>;

export function SubmitPassphrase(arg1:string):Promise<void>;

export function TerminalWrite(arg1:string,arg2:string):Promise<void>;

export function UpdateTunnel(arg1:config.TunnelConfig):Promise<void>;
