// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTunnel(arg1) {
  return window['go']['main']['App']['AddTunnel'](arg1);
}

export function CancelSFTPTransfer(arg1) {
  return window['go']['main']['App']['CancelSFTPTransfer'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearTunnelLogs(arg1) {
  return window['go']['main']['App']['ClearTunnelLogs'](arg1);
}

export function CloseSFTP(arg1) {
  return window['go']['main']['App']['CloseSFTP'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function ConnectGroup(arg1) {
  return window['go']['main']['App']['ConnectGroup'](arg1);
}

export function ConnectTunnel(arg1) {
  return window['go']['main']['App']['ConnectTunnel'](arg1);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function DisconnectGroup(arg1) {
  return window['go']['main']['App']['DisconnectGroup'](arg1);
}

export function DisconnectTunnel(arg1) {
  return window['go']['main']['App']['DisconnectTunnel'](arg1);
}

export function ExportTunnels(arg1, arg2) {
  return window['go']['main']['App']['ExportTunnels'](arg1, arg2);
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetCloseToTray() {
  return window['go']['main']['App']['GetCloseToTray']();
}

export function GetConfigFiles() {
  return window['go']['main']['App']['GetConfigFiles']();
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetIncludedConfigFiles() {
  return window['go']['main']['App']['GetIncludedConfigFiles']();
}

export function GetTunnelLogs(arg1) {
  return window['go']['main']['App']['GetTunnelLogs'](arg1);
}

export function GetTunnelStatuses() {
  return window['go']['main']['App']['GetTunnelStatuses']();
}

export function GetTunnels() {
  return window['go']['main']['App']['GetTunnels']();
}

export function ImportPreview(arg1) {
  return window['go']['main']['App']['ImportPreview'](arg1);
}

export function ImportTunnels(arg1, arg2) {
  return window['go']['main']['App']['ImportTunnels'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function OpenSFTP(arg1) {
  return window['go']['main']['App']['OpenSFTP'](arg1);
}

export function OpenTerminal(arg1) {
  return window['go']['main']['App']['OpenTerminal'](arg1);
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SFTPDelete(arg1, arg2) {
  return window['go']['main']['App']['SFTPDelete'](arg1, arg2);
}

export function SFTPDownload(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownload'](arg1, arg2);
}

export function SFTPDownloadDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPDownloadDir'](arg1, arg2);
}

export function SFTPListDir(arg1, arg2) {
  return window['go']['main']['App']['SFTPListDir'](arg1, arg2);
}

export function SFTPMkdir(arg1, arg2) {
  return window['go']['main']['App']['SFTPMkdir'](arg1, arg2);
}

export function SFTPPickUploadFiles(arg1, arg2) {
  return window['go']['main']['App']['SFTPPickUploadFiles'](arg1, arg2);
}

export function SFTPReadText(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPReadText'](arg1, arg2, arg3);
}

export function SFTPRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPRename'](arg1, arg2, arg3);
}

export function SFTPUploadFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SFTPUploadFiles'](arg1, arg2, arg3);
}

export function SFTPWriteText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SFTPWriteText'](arg1, arg2, arg3, arg4);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetTunnelPinned(arg1, arg2) {
  return window['go']['main']['App']['SetTunnelPinned'](arg1, arg2);
}

export function SubmitPassphrase(arg1) {
  return window['go']['main']['App']['SubmitPassphrase'](arg1);
}

export function TerminalWrite(arg1, arg2) {
  return window['go']['main']['App']['TerminalWrite'](arg1, arg2);
}

export function UpdateTunnel(arg1) {
  return window['go']['main']['App']['UpdateTunnel'](arg1);
}
