// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function AddTunnel(arg1) {
  return window['go']['main']['App']['AddTunnel'](arg1);
}

export function ConnectTunnel(arg1) {
  return window['go']['main']['App']['ConnectTunnel'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['main']['App']['DeleteTunnel'](arg1);
}

export function DisconnectTunnel(arg1) {
  return window['go']['main']['App']['DisconnectTunnel'](arg1);
}

export function ExportTunnels(arg1, arg2) {
  return window['go']['main']['App']['ExportTunnels'](arg1, arg2);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetTunnelStatuses() {
  return window['go']['main']['App']['GetTunnelStatuses']();
}

export function GetTunnels() {
  return window['go']['main']['App']['GetTunnels']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ImportPreview(arg1) {
  return window['go']['main']['App']['ImportPreview'](arg1);
}

export function ImportTunnels(arg1, arg2) {
  return window['go']['main']['App']['ImportTunnels'](arg1, arg2);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveFile(arg1) {
  return window['go']['main']['App']['SelectSaveFile'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SubmitPassphrase(arg1) {
  return window['go']['main']['App']['SubmitPassphrase'](arg1);
}

export function UpdateTunnel(arg1) {
  return window['go']['main']['App']['UpdateTunnel'](arg1);
}
